name: PHPUnit

on: [ push, pull_request ]

jobs:
  ci:
    name: Test on PHP ${{ matrix.php-version }}
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' ]
      max-parallel: 7
    env:
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=0
          coverage: none
      - name: Show Environment
        run: |
          php -v
          php -m
          php -i
      - name: Setup Packages
        run: composer update -o
      - name: Run Test Cases
        run: |
          vendor/bin/php-cs-fixer fix --dry-run
